# netlify.toml

# Build settings
[build]
  # Directory to publish (the output of your build process)
  publish = "public"

  # Build command, if needed (for example, if you have a build process)
  command = "npm run build"  # Replace with your actual build command

# Basic build environment settings
[build.environment]
  NODE_VERSION = "14"  # Replace with the Node.js version you need

# Redirects settings (optional, for routing or custom 404 pages)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset optimization and settings (optional, enable if needed)
[build.processing]
  # Minify HTML, CSS, and JS files
  html = ["html"]
  css = ["css"]
  js = ["js"]

  # Asset optimization (automatic image and font optimization)
  images = true
  fonts = true

# HTTP/2 Server Push settings (optional, improve page load times)
[[headers]]
  for = "/*"
  [headers.values]
    Link = "</styles.css>; rel=preload; as=style, </script.js>; rel=preload; as=script"

# Headers settings (optional, configure response headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
